#!/usr/bin/env bash
# Deploy the UC2 OAuth mock token server.
# Issues user-identity JWTs for the AgentCore OBO exchange.
# Creates an API Gateway HTTP API as the public endpoint (Function URLs with
# AuthType: NONE are blocked by org SCPs on both internal Amazon accounts and
# Workshop Studio vended accounts).
# The handler validates client credentials (CLIENT_SECRET_BASIC) at the app layer.
set -euo pipefail
PROFILE="${AWS_PROFILE:-}"
REGION=us-east-1
ACCOUNT="$(aws sts get-caller-identity ${PROFILE:+--profile "$PROFILE"} --query Account --output text)"
FN=oauth-mock-server
LAMBDA_ROLE=OAuthMockServerRole
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VAULT_STANDIN="$HERE/../vault-standin"

# Client credentials for the OAuth token endpoint (AgentCore presents these)
CLIENT_ID="workshop-obo-client"
CLIENT_SECRET=[REDACTED_PASSWORD]

echo "[oauth-mock] account: $ACCOUNT"

# 1. Lambda execution role (minimal — just logs)
LAMBDA_TRUST='{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Service":"lambda.amazonaws.com"},"Action":"sts:AssumeRole"}]}'
if ! aws iam get-role --role-name "$LAMBDA_ROLE" ${PROFILE:+--profile "$PROFILE"} >/dev/null 2>&1; then
  aws iam create-role --role-name "$LAMBDA_ROLE" ${PROFILE:+--profile "$PROFILE"} --assume-role-policy-document "$LAMBDA_TRUST"
fi
aws iam put-role-policy --role-name "$LAMBDA_ROLE" ${PROFILE:+--profile "$PROFILE"} --policy-name logs \
  --policy-document "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":[\"logs:CreateLogGroup\",\"logs:CreateLogStream\",\"logs:PutLogEvents\"],\"Resource\":\"arn:aws:logs:${REGION}:${ACCOUNT}:*\"}]}"
LAMBDA_ROLE_ARN="arn:aws:iam::${ACCOUNT}:role/${LAMBDA_ROLE}"
sleep 10

# 2. Package (handler + private key + pyjwt)
BUILD="$HERE/build"; rm -rf "$BUILD"; mkdir -p "$BUILD"
cp "$HERE/handler.py" "$BUILD/"
cp "$VAULT_STANDIN/private.pem" "$BUILD/"
# Bundle jwks.json (generated by keygen.sh — must match private.pem)
if [ -f "$VAULT_STANDIN/jwks.json" ]; then
  cp "$VAULT_STANDIN/jwks.json" "$BUILD/"
else
  echo "[oauth-mock] WARNING: jwks.json not found. Run 'bash tools/keygen.sh' in applications/vault-standin/ first."
  exit 1
fi
python3 -m pip install pyjwt cryptography -t "$BUILD" --quiet \
  --platform manylinux2014_x86_64 --python-version 3.12 --implementation cp --only-binary=:all: --upgrade
( cd "$BUILD" && zip -qr ../mock-server.zip . )
ZIP="$HERE/mock-server.zip"

# 3. Build env vars JSON
# $1 = token_endpoint, $2 = issuer (optional, defaults to placeholder)
_build_env_json() {
  local token_endpoint="${1:-}"
  local issuer="${2:-PLACEHOLDER_ISSUER}"
  cat <<ENDJSON
{"Variables":{"ISSUER":"${issuer}","KID":"stage2-key-1","AUDIENCE":"vault-standin","AGENT_SUB":"uc1-agent","TOKEN_TTL":"900","CLIENT_ID":"${CLIENT_ID}","CLIENT_SECRET":"${CLIENT_SECRET}","TOKEN_ENDPOINT":"${token_endpoint}"}}
ENDJSON
}

ENVJSON=$(_build_env_json "")

# 4. Create/update Lambda
if aws lambda get-function --function-name "$FN" ${PROFILE:+--profile "$PROFILE"} --region "$REGION" >/dev/null 2>&1; then
  aws lambda update-function-code --function-name "$FN" ${PROFILE:+--profile "$PROFILE"} --region "$REGION" --zip-file "fileb://$ZIP" >/dev/null
  aws lambda wait function-updated --function-name "$FN" ${PROFILE:+--profile "$PROFILE"} --region "$REGION"
  aws lambda update-function-configuration --function-name "$FN" ${PROFILE:+--profile "$PROFILE"} --region "$REGION" \
    --environment "$ENVJSON" --handler handler.handler --runtime python3.12 --timeout 15 >/dev/null
else
  aws lambda create-function --function-name "$FN" ${PROFILE:+--profile "$PROFILE"} --region "$REGION" \
    --runtime python3.12 --handler handler.handler --timeout 15 \
    --role "$LAMBDA_ROLE_ARN" --zip-file "fileb://$ZIP" --environment "$ENVJSON" >/dev/null
fi
aws lambda wait function-updated --function-name "$FN" ${PROFILE:+--profile "$PROFILE"} --region "$REGION"
LAMBDA_ARN="arn:aws:lambda:${REGION}:${ACCOUNT}:function:${FN}"

# 5. API Gateway HTTP API (public endpoint — Function URLs blocked by org SCPs)
API_NAME=oauth-mock-api
API_ID=$(aws apigatewayv2 get-apis ${PROFILE:+--profile "$PROFILE"} --region "$REGION" \
  --query "Items[?Name=='${API_NAME}'].ApiId | [0]" --output text 2>/dev/null || echo "None")

if [ -z "$API_ID" ] || [ "$API_ID" = "None" ]; then
  echo "[oauth-mock] Creating API Gateway HTTP API..."
  API_ID=$(aws apigatewayv2 create-api --name "$API_NAME" --protocol-type HTTP \
    ${PROFILE:+--profile "$PROFILE"} --region "$REGION" --query 'ApiId' --output text)

  INTEGRATION_ID=$(aws apigatewayv2 create-integration --api-id "$API_ID" \
    --integration-type AWS_PROXY --integration-uri "$LAMBDA_ARN" \
    --payload-format-version "2.0" \
    ${PROFILE:+--profile "$PROFILE"} --region "$REGION" --query 'IntegrationId' --output text)

  aws apigatewayv2 create-route --api-id "$API_ID" \
    --route-key '$default' --target "integrations/${INTEGRATION_ID}" \
    ${PROFILE:+--profile "$PROFILE"} --region "$REGION" >/dev/null

  aws apigatewayv2 create-stage --api-id "$API_ID" \
    --stage-name '$default' --auto-deploy \
    ${PROFILE:+--profile "$PROFILE"} --region "$REGION" >/dev/null

  aws lambda add-permission --function-name "$FN" ${PROFILE:+--profile "$PROFILE"} --region "$REGION" \
    --statement-id ApiGatewayInvoke --action lambda:InvokeFunction \
    --principal apigateway.amazonaws.com \
    --source-arn "arn:aws:execute-api:${REGION}:${ACCOUNT}:${API_ID}/*" 2>/dev/null || true
else
  echo "[oauth-mock] API Gateway already exists: $API_ID"
fi

API_URL="https://${API_ID}.execute-api.${REGION}.amazonaws.com"

# 6. Update ISSUER + TOKEN_ENDPOINT to APIGW URL
ENVJSON=$(_build_env_json "${API_URL}/token" "${API_URL}")
aws lambda wait function-updated --function-name "$FN" ${PROFILE:+--profile "$PROFILE"} --region "$REGION"
aws lambda update-function-configuration --function-name "$FN" ${PROFILE:+--profile "$PROFILE"} --region "$REGION" \
  --environment "$ENVJSON" >/dev/null

echo
echo "============================================================"
echo "  OAuth Mock Server deployed."
echo "    Function: $FN ($LAMBDA_ARN)"
echo "    API Gateway: $API_URL"
echo "    Token endpoint: ${API_URL}/token"
echo "    Discovery: ${API_URL}/.well-known/openid-configuration"
echo "    JWKS: ${API_URL}/jwks.json"
echo "    Client ID: $CLIENT_ID"
echo ""
echo "  Test:"
echo "    curl -s -X POST ${API_URL}/token \\"
echo "      -u '${CLIENT_ID}:${CLIENT_SECRET}' \\"
echo "      -d 'grant_type=client_credentials' | python3 -m json.tool"
echo "============================================================"
